### ISSUE TITLE
Storyboarding

### ISSUE THREAD

**Issue by Al-Andrew** [4-Capybara-Fiorosi/CourtDate#2]
# Master wishlist:

- [x] Writing:
    - [ ] Level 1 

- [x] Meta-map design
   - [x] Block-level diagram
   - [x] Level 1 to neighbour levels connections

**Comment by andreitablan** [comment]
![Image](https://user-images.githubusercontent.com/76064833/225036775-c3c17ed1-065c-463a-96b2-a6c6e8a04871.png)

**Comment by Al-Andrew** [comment]
Most of the storyboarding done by @OpariucRares
